spring:
  datasource:
#    username: root
#    password: 121314
#    url: jdbc:mysql://112.31.48.184:3306/matools?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://192.168.110.134:3306/matools?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 121314
#    url: jdbc:mysql://localhost:3306/matools?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      max-wait: 6000
      max-active: 20
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  main:
    allow-circular-references: true
  messages:
    basename: validation/ValidationMessages

#  redis:
#    # 地址
#    #    host: 192.168.110.121
#    #    host: 192.168.110.134
#    host: localhost
#    # 端口，默认为6379
#    port: 6379
#    # 数据库索引
#    database: 0
#    # 密码
#    password:
#    # 连接超时时间
#    timeout: 10s
#    lettuce:
#      pool:
#        # 连接池中的最小空闲连接
#        min-idle: 0
#        # 连接池中的最大空闲连接
#        max-idle: 8
#        # 连接池的最大数据库连接数
#        max-active: 8
#        # #连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1ms

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  page-size-zero: true
  reasonable: true
server:
  port: 8700
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /

